### ISSUE TITLE
Demo is not working with simple xlsx file

### ISSUE THREAD

**Issue by jancha** [SheetJS/js-xls#100]
This worked on Friday http://oss.sheetjs.com/js-xls/, however the same test file is now producing errors. Same happens if I launch it locally.

Attached is console screenshot + test file.

Test environment: Mac OS X 10.11.5, Safari 9.1.1

<img width="793" alt="screen shot 2016-07-31 at 12 24 44" src="https://cloud.githubusercontent.com/assets/540255/17275712/f839e486-5719-11e6-91ff-de4516348317.png">
[test-xlsx.xlsx](https://github.com/SheetJS/js-xls/files/392334/test-xlsx.xlsx)

**Comment by reviewher** [comment]
This is an XLSX file, please use http://oss.sheetjs.com/js-xlsx/
