### ISSUE TITLE
ERROR in ./~/.npminstall/xlsjs/0.7.5/xlsjs/dist/cpexcel.js

### ISSUE THREAD

**Issue by Gavin-YYC** [SheetJS/js-xls#104]
hi:

I use the js-xls with webpack and npm, and I install it with "npm install xlsjs".

here is my webpack.config.js:

```
var path = require('path');
module.exports = {
    entry: path.resolve(__dirname, "src/js/index.js"),
    output: {
      path: path.resolve(__dirname, 'dist/js'),
      filename: 'bundle.js'
    },
    resolve: {
      extensions: ['', '.js'],
      alias: {
        jquery: 'src/lib/jquery.min.js'
      }
    },
    node: {
      fs: "empty"
    }
};
```

when I input "webpack" in CLI to run the app, I got some error info like this:

```
ERROR in ./~/.npminstall/xlsjs/0.7.5/xlsjs/dist/cpexcel.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./cptable in /Users/yangyoucun/Documents/jsExcel/node_modules/.npminstall/xlsjs/0.7.5/xlsjs/dist
 @ ./~/.npminstall/xlsjs/0.7.5/xlsjs/dist/cpexcel.js 807:16-41
```

How can I fix it ?

**Comment by xiaofuchuan** [comment]
Me too

**Comment by reviewher** [comment]
[js-xlsx](https://github.com/SheetJS/js-xlsx/) is a drop-in replacement for this library and includes support for additional formats like XLSX and XLSB.  We have resolved the issue there.  At some point we will roll out an update here, but we highly recommend migrating :)
