### ISSUE TITLE
Custom table formats?

### ISSUE THREAD

**Issue by gavinrobertszeco** [SheetJS/js-xls#105]
Hi there,

As a temporary solution, I have had to modify the source files to change the date/time formats within the `table_fmt` variable to suit my needs, however this is FAR from ideal.

Have I completely missed where the ability to provide these as an option, or does this yet not exist?

I'm using both the XLS and XLSX projects, which both use SSF, however it looks like that `table_fmt` is used outside of SSF to format the cell values.

Before I go making any PR's, could you clarify whether this is supported?

Thanks

**Comment by reviewher** [comment]
This is an issue for the formatting library https://github.com/SheetJS/ssf -- I will copy the issue over there.

FYI you should migrate over to https://github.com/SheetJS/js-xlsx -- the XLS and other format parsers have been merged and it presents the same API as this library.  It should be a drop-in replacement.
