### ISSUE TITLE
web workers fail to read xlsx

### ISSUE THREAD

**Issue by kenshinsoto** [SheetJS/js-xls#107]
In the live demo i try to read an xlsx file with "Use Web Workers: (when available)" cheked and the console print: 
TypeError: s is undefined
http://oss.sheetjs.com/js-xls/xlsworker2.js line 15
when  "Use Web Workers: (when available)" uncheked the console print:
uncaught exception: Unsupported file
But an xls is parsed with no problem.
[ContratosAnterioresEjemplo.xlsx](https://github.com/SheetJS/js-xls/files/720824/ContratosAnterioresEjemplo.xlsx)

**Comment by reviewher** [comment]
@kenshinsoto js-xls is for the XLS file format.  We have since merged the functionality into js-xlsx.  Can you check against the js-xlsx project https://github.com/SheetJS/js-xlsx -- the demo is at http://oss.sheetjs.com/js-xlsx/

**Comment by reviewher** [comment]
This is an XLSX file and works in the js-xlsx web demo as well as node module.  Please switch over.
