### ISSUE TITLE
don't want sorted json to be return after sheet_to_json 

### ISSUE THREAD

**Issue by KumarRajat** [SheetJS/js-xls#108]
HEY GUYS ,
i am having the same problem and not able to correct the issue . i am getting sorted key json but i don't want sheet_to_json method to return me sorted can u pls help me with the corrected code.

**Comment by reviewher** [comment]
JS objects have no innate sense of "key order".  You are seeing the keys in the order that your browser or node generates.  If you want the raw data, you can pass the argument `{header:1}` and get a raw array of arrays that you can walk manually.
