### ISSUE TITLE
The live-demo page doesn't work with a simple 1page excel sheet that I am entering. It was working yesterday but not now

### ISSUE THREAD

**Issue by RezaKaj** [SheetJS/js-xls#110]
# THIS PROJECT HAS BEEN MERGED INTO js-xlsx

If you have not doneso already, please upgrade! js-xlsx is compatible with the
full js-xls API and has additional features like XLSX support.  The browser code
additionally exports the XLS variable so there is no need to rewrite existing
client code!

Repo: [https://github.com/sheetjs/js-xlsx](https://github.com/sheetjs/js-xlsx)

Node module: [xlsx](https://npm.im/xlsx)

Issues reported here may be missed, and most replies will direct you to upgrade
to js-xlsx first.

**Comment by SheetJSDev** [comment]
We made no changes in the last three months ... can you share an offending file?  And as the message says, you really should switch up to js-xlsx (page is http://oss.sheetjs.com/js-xlsx/ )

**Comment by reviewher** [comment]
Test against http://oss.sheetjs.com/js-xlsx/ and raise an issue with https://github.com/sheetjs/js-xlsx/issues if you see the same problem
