### ISSUE TITLE
Can I use xls.writeFile(callback)?

### ISSUE THREAD

**Issue by liwenzhu** [SheetJS/js-xls#36]
I think it will be wonderful if I can save a xls file like:
xls.writeFile(function(err){}); or specify a new file name xls.writeFile('aaa', function(err){});

Can I use it like that now?

**Comment by SheetJSDev** [comment]
@liwenzhu @irfanyounas @geraltrivyan @sixquarks @recalccc migrating the issue to the XLSX tracker
