### ISSUE TITLE
Encryption scheme unsupported

### ISSUE THREAD

**Issue by pc-rgundlapalli** [SheetJS/js-xls#45]
The documentation does say that this module supports only XOR encryption. I have an excel sheet that is password protected and I am receiving "Encryption scheme unsupported". How can i fix this ??

I am the owner of the excel file and can password protect it the way that is supported by the module. I just do not know how to do it. Would you know how i can password protect the excel file to make it work with this module.

Thanks very much and great work
Ravi

**Comment by SheetJSDev** [comment]
@pc-rgundlapalli @libito @mwillism issue will being tracked in the XLSX tracker

**Comment by cubbuk** [comment]
Hi, is there any development in this issue? When we try to open a XLS file which is password protected we encountered the same exact error.

**Comment by scopsy** [comment]
+1

**Comment by og24715** [comment]
+1
