### ISSUE TITLE
IE8 cell.w formatted cell value missing

### ISSUE THREAD

**Issue by saw792** [SheetJS/js-xls#55]
Hi,

js-xls has an issue in IE8 where the formatted value of cells is not added to the cell object. I've traced this down to the `eval_fmt` function:

    function eval_fmt(fmt, v, opts, flen) {
	    var out = [], o = "", i = 0, c = "", lst='t', q, dt, j, cc;
	    var hr='H';
	    /* Tokenize */
	    while(i < fmt.length) {
		    switch((c = fmt[i])) {
                    ...
                    }
             ...
            }
        ...
    }

IE9 and below don't support accessing a string using array syntax (e.g. `c = fmt[i]`). I propose converting the string to an array, although I am not sure what impact that would have on efficiency.

**Comment by SheetJSDev** [comment]
@saw792 I'm going to close this and track it in the XLSX module
