### ISSUE TITLE
readAsArrayBuffer vs. readAsBinaryString

### ISSUE THREAD

**Issue by hatpick** [SheetJS/js-xls#58]
Hi,

To make sure my app is compatible with IE I use readAsArrayBuffer and it works smooth with the XLSX, however it doesn't work with XLS unless I use readAsBinaryString, any idea what might be the issue here?

Thanks,

**Comment by SheetJSDev** [comment]
@hatpick closing now, the plan is to fold the xls library into the xlsx library so that should obviate this problem
