### ISSUE TITLE
Uncaught Error: Encryption scheme unsupported

### ISSUE THREAD

**Issue by calebiosu** [SheetJS/js-xls#61]
I am trying to open an Excel 95-2004 password protected xls file and I get the console error, Uncaught Error: Encryption scheme unsupported. I was wondering why that could be? I saw that these excel files use RC4 Encryption and looking through the code I see a method parse_RC4CryptoHeader(), is that not the method that would decrypt the file?

**Comment by SheetJSDev** [comment]
@calebiosu issue will being tracked in the XLSX tracker
