### ISSUE TITLE
Limit the data area

### ISSUE THREAD

**Issue by RomanShabanov** [SheetJS/js-xls#63]
First of all, fantastic library! Good job!

The "issue" is not the case, it's more a suggestion.

1. The user browse/drops the excel file.
2. Modal window requests to specify:

2.1 Header row(optional) - e.g. A2:D2
2.2 Data area(required) - e.g A3:D400

3. Checkbox "Until the first blank row" (in case user has multiple tables on 1 page)

I am working with very big files and reading the entire file if the user requires only first 3(!) rows takes too much time. What I have done is I break the sequence before the cell parsing and return the sheets array so user could select a reading sheet as well. When all data is gathered, here is the tricky part, I start the reading again with limits set, where cell has to match chosen sheet and r:c limits. It's definitely not the best solution, but if you want I could share it by the time I am done. I still have to run some testing.

P.S. For some reasons I could never achieve "d" as a cell type. So trying to fix that by creating my own cell pattern to match. 

P.S.S Very good job! Exquisite! 

P.S.S.S English is not my native language

**Comment by SheetJSDev** [comment]
I assume you are referring to http://oss.sheetjs.com, correct?  If so, that is doable but will have to wait a bit
