### ISSUE TITLE
Invalid encoding for special characters

### ISSUE THREAD

**Issue by ajuhos** [SheetJS/js-xls#64]
I have an xls file with special characters (á,é,ő and other national chars). The file is opened correctly by Excel and also by your online demo. But when I try to open it using NodeJS and xlsjs, then the encoding of the special characters get wrong. For example after exporting to CSV from my code, none of the codepages of Excel would display these characters correctly anymore

**Comment by SheetJSDev** [comment]
@ajuhos can you share a sample file that shows the problem?

**Comment by ajuhos** [comment]
I've upgraded my problem description. As it seems like it is a problem only when using your library from Node, because my files are working in the online example, but not from Node. I cannot send you the file publicly as it contains sensitive information and if I change it in Excel, then after saving the encoding issue is gone. SO it is a problem with the encoding of the file itself, it is generated by a code I cannot alter. What is interesting that the browser version handles it correctly.

**Comment by SheetJSDev** [comment]
@ajuhos can you run the following (in the REPL or as a standalone script in node) and report the output:

```
var filename = "--put filename here--", sheetname = "-- put sheetname here --", celladdr = "-- address of cell with problem e.g. A1--";
var XLS = require('xlsjs')
console.log(XLS.version)
var wb = XLS.readFile(filename)
console.log(wb.Props.CodePage) // <-- this shows the codepage for the file
console.log(wb.Sheets[sheetname][celladdr]) // <-- this shows what js-xls thinks is in the cell
```

**Comment by ajuhos** [comment]
This is the output:
0.7.2
undefined
{ v: 'L?szl?n?',
  ixfe: 15,
  t: 's',
  XF:
   { ifnt: 0,
     ifmt: 0,
     flags: 0,
     fStyle: 0,
     data: { patternType: null, icvFore: 64, icvBack: 65 } },
  w: 'L?szl?n?' }

'L?szl?n?' should be 'Lászlóné'

**Comment by SheetJSDev** [comment]
@ajuhos Can you check the language settings on the computer running Excel?  In XP and Windows7 the setting is called "Language for non-Unicode programs":

- In windows7 go to the control panel .. Region and Language .. Administrative and you will see an item "Language for non-Unicode programs"
- In windows XP go to control panel .. Region and Language Options .. Advanced and you will see the same table.

Also, if I may ask, what tool generated the file?

**Comment by ajuhos** [comment]
Language for non-Unicode programs is set to "magyar (Magyarország)", in English it should be: "Hungarian (Hungary)". 

The file is coming form a GET request to an API which is not controlled by me and not documented at all, so I don't know anything about the generator tool.

**Comment by ajuhos** [comment]
If I set the codepage to 1200 manually, then all special chars of my files gets displayed correctly.

For now I changed the set_cp method in your code:
function set_cp(cp) { cp = 1200; console.log('SET_CP', cp); current_codepage = cp; if(typeof cptable !== 'undefined') current_cptable = cptable[cp]; }

Is there a public option for setting the codepage? I did not see it in the documentation.

**Comment by SheetJSDev** [comment]
@ajuhos at the moment there is no exposed manual override.  It would also likely work with code page 65001 (UTF8) because the characters in question share the same UCS2 and UTF16 and UTF8 representation compared to codepage 1250 and 1252.

If you can control the input source, can you try feeding it a name with "Ĺ" (which you can generate with `String.fromCharCode(313)`)?  I chose this character because it is in CP1250 (hungarian) but not in CP1252 (english).  It also has a 2 byte representation in UTF16 and a different 2-byte representation in UTF8.

**Comment by ajuhos** [comment]
I've tried 65001, 65000 (utf-7), 1250, 1251, 1252, 852, 858, 1047 and also all iso-8859-*  codepages (I've replaced the cpexcel module, with the full codepage module). The only working codepage was 1200. The char you've sent is not a Hungarian char so it is not in my input. But it seems like for me that the ő/Ő char is also a great character for testing, as while most of the chars worked in almost every codepage I've listed, this one is only in 1200.

**Comment by SheetJSDev** [comment]
I checked against the 6 files in our test suite that are missing the required codepage record, and there appears to be no issue with setting the default to 1200, so I wouldn't mind changing the default.

**Comment by shakhal** [comment]
Hello, 
I seem to have a somewhat similar problem... 
I'm trying to parse a Hebrew xls file, where I guess the CodePage was set to a wrong value...
Going through the code I see that set_cp sets CodePage value to 1252 which comes out as gibberish.. like OP, only overriding set_cp with hardcoded value of 1200  outputs the desired result...
and like OP, If I open the file with MS Excel and save it again, it seems to fix the correct CodePage value to 1200.

when I ran your suggested report I got:
0.7.3
1200
{ v: 'éâÕè ÞàÛáÙ ÔéçâÔ',
  ixfe: 21,
  t: 's',
  XF:
   { ifnt: 5,
     ifmt: 0,
     flags: 1,
     fStyle: 0,
     data: { patternType: 'solid', icvFore: 40, icvBack: 64 } },
  w: 'éâÕè ÞàÛáÙ ÔéçâÔ' }

but I suspect that it is not really using 1200 CodePage, since when I override set_cp with hardcoded 1200 I do get the desired for the same report:
0.7.3
1200
{ v: 'שעור מנכסי השקעה',
  ixfe: 21,
  t: 's',
  XF:
   { ifnt: 5,
     ifmt: 0,
     flags: 1,
     fStyle: 0,
     data: { patternType: 'solid', icvFore: 40, icvBack: 64 } },
  w: 'שעור מנכסי השקעה' }

You can find the file here:  https://drive.google.com/file/d/0B6llEMHOwN2_S3J6cDlUaE0zNTA/view?usp=sharing

TIA,
Shakhal

**Comment by SheetJSDev** [comment]
@shakhal thanks for sharing!  This file was very helpful.

There are various places in the spec which claim that the encoded string is Unicode, but in fact the string is codepage-encoded.  As a result, it was assumed (correctly, based on the test suite) that XLUnicodeRichExtendedString was also mistaken, however your file shows a valid case.  As a result, the best fix is to override the codepage just for the XLUnicodeRichExtendedString record.  That has been pushed to version 0.7.4-a on npm -- can you confirm that that works?

**Comment by shakhal** [comment]
@SheetJSDev works like magic :) thanks for your great work!

**Comment by shakhal** [comment]
oops, one more thing.. seems that problem persists for the sheet names...

**Comment by SheetJSDev** [comment]
Need to dig further: the spec points to ShortXLUnicodeString, which also says Unicode, but a few third-party writers use codepage strings for encoding sheet names.  Thanks for your patience, but we are trying to catch up to Excel-level robustness.

On a side note: would you grant permission for us to include the file in our test suite?  It would help a lot.

**Comment by shakhal** [comment]
@SheetJSDev Thanks for your prompt response.
I am not the author of this file, but it is freely available under the following link, so I guess you can 
use it for your testing purposes...
https://www.psagot.co.il/heb/PensionSavings/Lists/ProductForms/%d7%a8%d7%a9%d7%99%d7%9e%d7%aa%20%d7%a0%d7%9b%d7%a1%d7%99%d7%9d%20%d7%95%d7%a1%d7%a7%d7%99%d7%a8%d7%aa%20%d7%a8%d7%95%d7%97/%d7%a8%d7%91%d7%a2%d7%95%d7%9f%203%202014/%d7%a0%d7%9b%d7%a1%d7%99%d7%9d_845.xls

**Comment by shakhal** [comment]
@SheetJSDev would you consider adding an override flag for CodePage for the meanwhile...?

**Comment by SheetJSDev** [comment]
@shakhal the offensive test files actually were from an older version of the XLS standard (the so-called "BIFF5"), so that filter was added and I believe the latest version (0.7.5) should have the right logic.  Please confirm :)

**Comment by shakhal** [comment]
@SheetJSDev confirmed, again, thank you very much!
