### ISSUE TITLE
Is it possible to ignore a cell before JSON format ?

### ISSUE THREAD

**Issue by jeremydelacasa** [SheetJS/js-xls#65]
Thanks for this cool project !

I try to do something but i can't.

I have a file and i would like ignore a cell who is before my table. 
Because when i export to json, it just takes the column where there is the cell.

I don't want modify my file. 

Do you think is possible ?

Thank's a lot.

**Comment by SheetJSDev** [comment]
The sheet_to_json function takes a second options argument.  IF you set the `range` key to a number, it will start from specified row (0-indexed).  More information [in a js-xls issue which prompted the feature](https://github.com/SheetJS/js-xls/issues/42#issuecomment-44338791)

There are actually a few ways to control what cells to use:

- `XLSX.utils.sheet_to_json(ws, {range:3})` will skip the first 3 rows and use the remaining rows and columns

- `XLSX.utils.sheet_to_json(ws, {range:"A4:D7"})` will use the specified A1-reference-style range

- `XLSX.utils.sheet_to_json(ws, {range:{s:{r:1,c:0},e:{r:3,c:3}}})` will use the range object, whose form is described [in the README](https://github.com/SheetJS/js-xlsx/#general-structures)

To eliminate the headers, you can also set the header key to:

- `1`: generate array of arrays
- `"A"`: generate array of objects whose keys are the A1-style column labels (A,B,C,...,Z,AA,AB,...)
- array `["label1","label2",...]` use the specified labels as keys.

The relevant test case (which shows more use patterns) is [`json output`](https://github.com/SheetJS/js-xlsx/blob/master/test.js#L848)

If you know the structure of the file and you want a more custom output, you can write your own function.  https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L5255 is the code for the json output, which is fairly straightforward.

**Comment by jeremydelacasa** [comment]
You are the best !

I have used this <code>XLSX.utils.sheet_to_json(ws, {range:3})</code> and that work like a charm.

Thank you very much.

**Comment by SheetJSDev** [comment]
@jeremydelacasa closing now, for future issues please raise in the XLSX tracker https://github.com/SheetJS/js-xlsx
