### ISSUE TITLE
Date system incompatibility with .xls files from Mac Excel (1904 vs 1900)

### ISSUE THREAD

**Issue by Martin-Pitt** [SheetJS/js-xls#66]
I tried parsing an .xls file and the dates were all off, a compatibility report from the .xls file in Excel reports the following:

> Excel for Mac, like all Macintosh applications uses the 1904 date system to store dates in worksheets. Excel for Windows uses a different date system called the 1900 date system. Normally, each version of Excel automatically adjusts to use the correct date system. But, if you copied these dates from a worksheet created by Excel for Windows, the dates might appear off by as much as 4 years. For more information, click Help." 

I'm completely new to this library, so hope to have some advise or help on this.

**Comment by Martin-Pitt** [comment]
For now, I can change the workbook options to use the 1900 system (Preferences > Calculation > Workbook options, untick 'Use the 1904 date system.'.

Would be great if the library would be able to figure this out somehow though, as Excel is somehow able to figure out and convert the date systems automatically (I opened an .xls which was created on a windows system on a mac)

**Comment by Martin-Pitt** [comment]
I tried changing the system in the preferences, but that didn't help. The dates are off by 1462 days, so subtracting/adding that amount would correct them, unsure how to accomplish this though.

**Comment by Martin-Pitt** [comment]
The library appears to be able to understand that the workbook uses Date1904, but the option is not being sent around to parse_date_code to be aware of it. For now I have commented out
> /*if(opts.date1904)*/
to get my .xls files parsed correctly on my mac.

Also note inconsistent case of 'date1904' vs 'Date1904' throughout code.

**Comment by SheetJSDev** [comment]
@Martin-Pitt thanks for pointing this out!

The internal field was called Date1904 but the formatting parameter was called date1904 to be consistent with their documentation (you would think an organization would be consistent, but that's wishful thinking).  I haven't decided what the parameter will be, but I adjusted the format function to pass the 1904 parameter through.  This *should* resolve the issue, but the question about the case will be discussed in a separate issue in js-xlsx
