### ISSUE TITLE
why is readFile synchronous by default, not async?

### ISSUE THREAD

**Issue by jmarca** [SheetJS/js-xls#68]
It is surprising to me, given that node.js is by design async, that readFile uses readFileSync (see https://github.com/SheetJS/js-xls/blob/master/xls.js#L7121).  

At the very least, I would have expected readFile to be called "readFileSync."  Otherwise I think you're breaking the usual node.js customs. 

Apologies if this was already hashed out in a flame war somewhere.  I searched the issues and didn't find anything.

**Comment by SheetJSDev** [comment]
There was no flame war, surprisingly enough.  I do get emails about it from time to time, so a public comment isn't a bad idea (especially since it hasn't been discussed before)

Basically, "we made the decision very early on, and now it's very hard to change". 

The project originally was a browser library (back in 2012) and we called the "sync" version of the parser `read`.  It was easier because the HTML5 File API gives access to the entire data blob at once, so during development it was easier to store values and tinker directly.

When we discovered and started playing with node back in 2012, the original goal was to make a script we could use in the command line.  The module wasn't designed to be used outside of the shell command, and in many ways the development process is playing out with [js-harb](https://github.com/SheetJS/js-harb).  We built the `xls` (and eventually the `j`) script by tinkering on the REPL, and honestly it's much easier to work synchronously there.  We never really used the async file reading in the early days so it made sense to just call the sync version `readFile`.

As we started to explore node and engage with the community, we finally resigned ourselves to the conclusion that the greater node community actually favors async style (and that we were outliers in preferring the sync style).  That left us with a hard decision.  We didn't want to change the original `read` to `readSync`, and felt it was easier to just keep `readFile` sync rather than make both `read` and `readFile` async.  (it might have been even more confusing, imho, if we left `read` as sync and `readFile` as asynchronous.)

Had we started in 2015, with more experience and awareness of the community and browser and server-side APIs, we probably would have made read and readFile async.

**Comment by jmarca** [comment]
I get what you're saying.  I looked at the code last night and there are a lot of things to change to make it async and/or streaming/event-based parser.  (For example, in the xlsx project, the jszip library you're using isn't async or streaming either, but switching to something like [decompress-zip](https://github.com/bower/decompress-zip) would be tedious, esp when trying to preserve browser based functionality.)

Still, as a node.js user, I would prefer to see a function called "readFileSync" rather than "readFile"  I totally get "don't break everybody's code", *but*... you're not currently exporting "readFileSync" so you could just do

```javascript
XLS.read = xlsread;
XLS.readSync = xlsread;
XLS.readFile = readFile;
XLS.readFileSync = readFile;
```

And then in the docs for the API say:

```
readFile:  deprecated usage, see readFileSync

readFileSync: [blah blah blah]

```

I know this is purely cosmetic, but it is more consistent with node.js semantics.

I actually sort of *have to* use a streaming interface so as not to load all of the spreadsheets I'm processing in RAM.  I'm abandoning my old Perl code because I need to do that.

Feel free to close this issue.

**Comment by SheetJSDev** [comment]
The issue of streaming was discussed in the `j` project: https://github.com/SheetJS/j/issues/3

Basically, there are third-party writers who try to be overly clever and write critical metadata at the end rather than at the beginning of the container file, which means you have to basically read the entire file and buffer it before processing.  If "XLS" and "XLSX" meant only files that Excel generated, then this would not be a problem.

**Comment by notatestuser** [comment]
That seems solvable though (stream to disk, catch metadata, make second pass from disk with knowledge of metadata).

**Comment by SheetJSDev** [comment]
@notatestuser Like https://github.com/SheetJS/j/blob/master/bin/j.njs#L73-L87 ? I wouldn't mind porting it over and possibly making it a part of the module rather than a code block in the binary

**Comment by jmarca** [comment]
Thanks for the pointer to that.  

on @notatestuser's point,  It seems a similar two pass approach is used by the perl module Spreadsheet::ParseExcel (http://search.cpan.org/~dougw/Spreadsheet-ParseExcel-0.65/lib/Spreadsheet/ParseExcel.pm#Reducing_the_memory_usage_of_Spreadsheet::ParseExcel)

**Comment by notatestuser** [comment]
Ah that's interesting. Shame about the dependency on a filesystem though (is anyone parsing Excel on a tessel? ;) )

**Comment by SheetJSDev** [comment]
@jmarca if I understood the post correctly, they are discussing "OLE extraction" but aren't saying they are writing to file:

> In the first stage it extracts the Excel binary stream from the OLE container file using OLE::Storage_Lite. 

We essentially do the same thing now (that's the point of the CFB code, the new name for the OLE format).  Do you know if they actually write the individual streams to file?

a quick search for "tmp" or "temp" in https://github.com/gitpan/Spreadsheet-ParseExcel reveals no obvious call to create a temporary file

**Comment by SheetJSDev** [comment]
Actually, looking at OLE::Storage_Lite, there is no obvious temp file reference there either.

cc @jmcnamara @dougwilson I'm guessing you are the authors of Spreadsheet::ParseExcel and OLE::Storage_Lite.  Are temporary files used in XLS processing?

**Comment by jmarca** [comment]
I agree with you.  As far as I can tell, they do *not* write out to a temp file, but rather just do a two pass look at the data (and since I'm just coming at this from a user's perspective, I'm sure you can understand their code a lot better than I can).

There is a module Spreadsheet::ParseExcel::Stream that implies that it is streaming but really it just wraps the Spreadsheet::ParseExcel as mentioned in the link I gave above with a custom cell handler that doesn't do much, so as to reduce memory overhead.

And I think @runrig has the current maintenance responsibilities for Spreadsheet::ParseExcel at https://github.com/runrig/spreadsheet-parseexcel

Again, I was moving from perl to node.js thinking I would have an easier time finding a streaming parser, but as you pointed out, this is more difficult than simply reading through the file line by line.

If I were to do it (I know nothing) I would read once line by line to suss out the correct dictionary stuff, emitting events as necessary for those type events, and stream the file into a temp file.  Then open a new stream on that temp file to actually parse the file with the knowledge gained from the first pass, with the "metadata all at the top" forming a special case that means the first pass is faster.


But again, I'm clueless about the XLS and XLSX specs, so maybe that is hopelessly naive.

**Comment by dougwilson** [comment]
> cc @jmcnamara @dougwilson I'm guessing you are the authors of Spreadsheet::ParseExcel and OLE::Storage_Lite. Are temporary files used in XLS processing?

My CPAN name is actually "DOUGDUDE" :) so DOUGW is someone different, haha.

**Comment by SheetJSDev** [comment]
@dougwilson sorry about that, http://search.cpan.org/~dougw/ notes the name as "Douglas Wilson" and you are the only one who shows up in a github search for the name: https://github.com/search?q=douglas+wilson&ref=searchresults&type=Users

**Comment by SheetJSDev** [comment]
@jmarca I actually wrote a blurb about it in response to a bug in PHPExcel (took me a while to find): https://github.com/PHPOffice/PHPExcel/issues/260#issuecomment-61432748

Long story short, the file is really a sequence of 512-byte blocks.  Each block generally has a pointer to the next block in sequence (or a special end of chain flag to indicate the sequence is done), so you can think of the "chain" of blocks like a linked list.  Special directory sectors tell you where the files start.

PHPExcel cheats by doing two things that really lean on Excel's robustness and preclude a true streaming solution:

- the directory sectors are written at the end, which means you need to read to the end of the file before knowing which set of blocks correspond to which logical file.
- even if you decided to guess the blocks corresponding to the workbook, the logical files don't start at the beginning of each chain.  In the case from that issue, the actual workbook file starts at the third block in the chain, not the head.

So the only way to do really this in a streaming manner is to make a series of guesses.  That, or just buffer (which is what https://www.npmjs.com/package/excel-stream does).  Of course, in this case we can also try to convince @PHPOffice to fix the problem, but that won't change the multitude of files in the wild.

**Comment by jmarca** [comment]
I really don't see what is going on in excel-stream.  It looks to me like it writes the stream to a temp file, then pipes that through your executable, and I can't see what it offers in terms of reducing RAM usage, etc.  I need to run it on a test file I guess and step through what it is doing.

And I also don't understand how your code is parsing excel files, and I think it would be best for me to either study the code or shut up.  And since decoding excel is extremely far removed from what I do, I'll probably just shut up and stop offering non sequitur type suggestions.

Really, the point of this bug is to request that the *naming* of the exported function change to include the word "Sync" so that newcomers with a node.js point of view won't be confused and wonder why it isn't async.  I think all this streaming stuff I brought up is better in another issue topic.

**Comment by SheetJSDev** [comment]
@jmarca First step: v0.7.5 includes readFileSync and readSync (as aliases to readFile and read respectively)

**Comment by fabiooshiro** [comment]
is there any async reader?

**Comment by reviewher** [comment]
We may add some async support to js-xlsx in the future.  Since the functionality from js-xls has been folded into js-xlsx, we can discuss more in that issue tracker

**Comment by peeyushsrivastava** [comment]
Is there any update on this? Is this issue has been fixed as I can see it still using sync approach for reading file.

**Comment by reviewher** [comment]
@peeyushsrivastava js-xls was completely merged into js-xlsx, there is no reason to use this module directly at this point.

Reading is computationally intensive.  The best approach for async is to use a child process and run the logic from there

**Comment by peeyushsrivastava** [comment]
fferYeah I was looking for the same in js-xlsx but found similar question here so just want to check whether it was closed or not ,actually js-xslx still following sync nature what I got from the code. Definitely invoking a child process is a good option but in browser file upload there will be so many requests for upload which can hamper performance at certain point , so I am trying using js-xlsx in combination with fs node buffer as fs helps me to read file asynchronously and after that passing buffer to js-xlsx to convert it into json. Please advise on this solution.

**Comment by reviewher** [comment]
In the browser you can use web workers.  The actual work will happen outside of the main thread.  The demo http://oss.sheetjs.com/js-xlsx/ shows how it's done.
