### ISSUE TITLE
why XLS.utils.sheet_to_row_object_array(workbook.Sheets[sheetName]) by default return sorted row object property

### ISSUE THREAD

**Issue by anilapu** [SheetJS/js-xls#69]
Hi,

When i am using XLS.utils.sheet_to_row_object_array(workbook.Sheets[sheetName])  returns sorted row property. How can i get unsorted row property?
Here i am getting sorted data as : 
![sorted_property](https://cloud.githubusercontent.com/assets/9476474/6285201/f0a33d70-b91e-11e4-9a89-26a3c5c6279f.png) 
When actual file contains data as : 
![original_property](https://cloud.githubusercontent.com/assets/9476474/6285256/92dc7246-b91f-11e4-95e6-c872a242c41b.png)

**Comment by SheetJSDev** [comment]
There is no true sense of "key ordering" in JS objects.  V8 may do some magic here, but in general the spec does not require any ordering.  This is in contrast to, say, collections.OrderedDict in python (which does keep track of when fields are added).

You could generate an ordered list by by walking through the first row, which is how the utility finds the headers: https://github.com/SheetJS/js-xls/blob/master/xls.js#L7262-L7273

You could also just use sheet_to_json and set the header field of the options object to 1, which would generate an array of arrays.

**Comment by anilapu** [comment]
Thank you @SheetJSDev. I am unable to find which function is reordering options object but i have added my piece of code according to my requirement. Now i can able to get data in desired way.

**Comment by KumarRajat** [comment]
HEY GUYS ,
i am having the same problem and not able to correct the issue . i am getting sorted key json but i don't want sheet_to_json method to return me sorted can u pls help me with the corrected code.
