### ISSUE TITLE
Not able to parse a excel file

### ISSUE THREAD

**Issue by SolaiappanRajendran** [SheetJS/js-xls#70]
I am getting the below exception in line no xls.js at 4022 line no.

Uncaught Unrecognized Formula Token: PtgAreaErr3d,1,0.

Can anyone help me on this?

**Comment by SheetJSDev** [comment]
@SolaiappanRajendran would it be possible to share a file that shows the error?  Ideally, if you can strip confidential information, we can add it to the test suite.

That error should show up if the formula in question contains an invalid 3d reference (e.g. the range B2:C3 in every worksheet), but for some reason Excel 2013 was not generating that specific token when I made the error test case.  The short-term solution is just to break in that case (like how PtgRefErr3d is ignored in https://github.com/SheetJS/js-xls/blob/master/xls.js#L4024)
