### ISSUE TITLE
s2ab function parameter is undefined

### ISSUE THREAD

**Issue by trixtur** [SheetJS/js-xls#73]
This is causing the worker to fail.

Oh.. sorry this issue is for the demo site.

**Comment by trixtur** [comment]
I figured out the problem. I was using the wrong type of excel sheet. I used xlsx on an xls parser. It would be nice if it didn't fail silently.

**Comment by SheetJSDev** [comment]
@trixtur the parsing logic is now folded into js-xlsx 0.8.0, so now the worker should not fail.  Going to close the issue here, if you notice any problems please raise them in https://github.com/SheetJS/js-xlsx
