### ISSUE TITLE
parse this xls file wrong with chinese

### ISSUE THREAD

**Issue by ifeiteng** [SheetJS/js-xls#74]
When i parse this [xls](http://static.feit.me/b19电化1203hz.xls) file, the chinese is messy, please help me...

**Comment by SheetJSDev** [comment]
I tried opening this in Excel 2013 and the characters look like junk (screenshot included).  I also tried opening this in Excel 2011 and it warns "File error: data may have been lost."

What version of Excel did you use to generate this file?  Can you share a screenshot of the entire worksheet and can you save the file in a different format (like CSV or text) as a baseline?

![](http://i.imgur.com/G5bLStV.png)

**Comment by ifeiteng** [comment]
this file is download from my school website, charset maybe gbk, i think this file is generate by program, version 2003
![1d90 tmp](https://cloud.githubusercontent.com/assets/4183342/6654434/f2c767ce-cafe-11e4-8cf7-bc4a70e0d06a.png)
this is my parse result
![2721 tmp](https://cloud.githubusercontent.com/assets/4183342/6654447/38bfc608-cb00-11e4-8e3f-4eaef14a32ae.png)

**Comment by ifeiteng** [comment]
oh, this file is Microsoft Excel 5.0/95
