### ISSUE TITLE
 About ko-kr FormatCode incorrect Issue

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xls#76]
I'm a korean developer.

I am using xlsjs(v0.7.5).

I expected the correct formatcode about ("yyyy-mm-dd") date Format.

But always rendered data is mm/dd/yy that is formatcode 14...

In . ECMA-376

ko-kr "yyyy-mm-dd" formatcode is 34, 35, 52, 53, 55, 56

I want to get correct formatcode about "yyyy-mm-dd" ko-kr date Format.

Is there I missing step on locale setting at sheetjs??

I'm waiting your Response

**Comment by SheetJSDev** [comment]
Discussion at https://github.com/SheetJS/js-xlsx/issues/200
