### ISSUE TITLE
Mobile and desktop browser differences mean XLS.js runs differently because of Array.protoype.find

### ISSUE THREAD

**Issue by xrd** [SheetJS/js-xls#80]
I'm trying to use XLS.js inside a mobile app powered by Cordova.

When I run the app, attaching Safari web tools and debugging through it, I can see a different crash inside `parse_xlscfb`. On desktop browsers, the call to test [`cfb.find`](https://github.com/SheetJS/js-xls/blob/master/xls.js#L6329) fails (the method does not exist inside of an array object). On mobile devices it does find this method (Array.prototype.find exists), but the syntax is incorrect and I get a crash (something like `find@[native code]`).

The same error seems to occur on any mobile browser (chrome or safari). 

According to the find method [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), the first parameter to `find` should be a callback; these calls all provide a string.

Is there a polyfill I need to install for xls.js when running inside a mobile browser? I did use shim.js, but I don't see it changing the array prototype.

**Comment by SheetJSDev** [comment]
@xrd good timing since I'm looking into some CFB issues right now.

Let's verify that mobile works: does http://oss.sheetjs.com/js-xls/ajax.html work on mobile chrome and safari?  This page attempts to download an XLS file using XHR and show the CSV contents.  The page source is [in the gh-pages branch](https://github.com/SheetJS/js-xls/blob/gh-pages/ajax.html)

I'm not too familiar with cordova.  Can you share a minimal cordova app that shows this problem?

Note: The actual cfb object should have the find function: https://github.com/SheetJS/js-xls/blob/master/xls.js#L1457 -- it's a separate search function based on [MS-CFB] 2.6.4

**Comment by xrd** [comment]
Hmm, I used some test data on both Chrome desktop and Safari on iOS and they both worked. Perhaps my other test file (unfortunately I cannot share quite yet) is troublesome. I will try to get a clearly reproducible test case for you, but this might have been my user error. Thanks for your response.

**Comment by SheetJSDev** [comment]
@xrd if you think there may be an issue with parsing your test file, could you try reproducing this ajax test using your file?  To do that:

- clone this repo, checkout the gh-pages branch
- copy your test file into that directory and edit ajax.html: change the line `var url = "test_files/formula_stress_test_ajax.xls";` to point to your test file.
- spin up a local webserver and go to ajax.html.  using python, `python -mSimpleHTTPServer` will start a web server on port 8000, so you can then go to http://localhost:8000/ajax.html

**Comment by xrd** [comment]
I forked the repository to github.com/xrd/js-xls. The formula_stress_test_ajax.xls file points to a dummy file that crashes here, but works when I open it in Excel. Care to take a look?

**Comment by SheetJSDev** [comment]
@xrd thanks for sharing!  I am super excited to see this!  Do you mind if we add this file to the test suite?

This file follows a very old format that can't even be produced by modern versions of Excel.  If I recall correctly, they started phasing out this format in Excel 5.0 (more than 2 decades ago).  We don't have access to such an old version of Excel, so we've been working off of files that others have shared.

I can reproduce the issue in Chrome 42.0.2311.135 for Mac, although the error there is slightly different 
(`s.split is not a function`).  Strangely enough, it works fine on the computer when doing the click and drag dance with http://oss.sheetjs.com/js-xls (as well as with the node library)

**Comment by xrd** [comment]
Please add it! I'm thrilled to contribute to such a great project. I can
provide a Cordova project and debugging steps tomorrow.
