### ISSUE TITLE
sheet_to_json always returning formatted values

### ISSUE THREAD

**Issue by bimal1331** [SheetJS/js-xls#81]
How do I access raw values? We need floating point precison and sheet_to_json return truncated floats.
Looks like I can access raw value by workbook.Sheets[name]['I3'].v but no format option to pass in sheet_to_json method.

**Comment by reviewher** [comment]
The `sheet_to_json` function takes an options argument.  If you pass `{raw:true}` as the second argument it will give you the raw values.
