### ISSUE TITLE
How to create a simple workbook from custom data?

### ISSUE THREAD

**Issue by simar88** [SheetJS/js-xls#83]
Hi everyone,
i'm looking for something that can help to build an excel file from data that are stored in a mongoDB collection.
How can i build a workbook? I can't understand it.
Thanks in advance,
Simone

**Comment by comerc** [comment]
https://github.com/SheetJS/js-xlsx/issues/365

**Comment by reviewher** [comment]
This library has been merged into [js-xlsx](https://github.com/SheetJS/js-xlsx).  It exposes the same exact interface.  There are some write examples in that project.
