### ISSUE TITLE
Functionality, modify and save as?

### ISSUE THREAD

**Issue by SPlatten** [SheetJS/js-xls#85]
Is is possible to modify the cells and ranges of an existing workbook then save as a new workbook?

**Comment by leixu2txtek** [comment]
in node Yes !

see https://gist.github.com/SheetJSDev/88a3ca3533adf389d13c

**Comment by SPlatten** [comment]
Thank you, I'll take a look.


On 20 January 2016 at 08:32, Lei Xu <notifications@github.com> wrote:

> in node Yes !
>
> see https://gist.github.com/SheetJSDev/88a3ca3533adf389d13c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SheetJS/js-xls/issues/85#issuecomment-173128222>.
>



-- 
<http://about.me/SPlatten>


[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
  <http://about.me/SPlatten>

**Comment by reviewher** [comment]
If this issue persists, please migrate to [js-xlsx](https://github.com/SheetJS/js-xlsx) -- it's a complete drop-in replacement with additional format support.
