### ISSUE TITLE
Is there a way to write background color ?

### ISSUE THREAD

**Issue by leixu2txtek** [SheetJS/js-xls#86]
when I read file with 

``` javascript
xls.readFile(_this.config.file, { cellStyles: true })
```

I can get this 
![image](https://cloud.githubusercontent.com/assets/5109966/12443744/16bf3b76-bf95-11e5-8458-7e086ec0667c.png)

but when i save this workbook, the styles was gone.

so how can i save with the styles ..

Thanks..

**Comment by reviewher** [comment]
This is an XLSX issue.  Please raise issue at https://github.com/SheetJS/js-xlsx
