### ISSUE TITLE
XLS/XLSX excel column background color

### ISSUE THREAD

**Issue by LPRS** [SheetJS/js-xls#87]
To set alasql-XLS export excel column background color

**Comment by LPRS** [comment]
var mystyle = {
                sheetid: 'Task',
                headers: true,
                column: { style: 'background:#a8adc4 },
                };
 alasql('SELECT * INTO XLS("List.xls",?) FROM ?',
                        [mystyle, $scope.items]);

**Comment by reviewher** [comment]
This is an issue for alasql, I think their issue tracker is at https://github.com/agershun/alasql/issues
