### ISSUE TITLE
How to read image from xls file?

### ISSUE THREAD

**Issue by parthivpn** [SheetJS/js-xls#90]
I need to read image which i placed or inserted into one xls file. so while reading time i need to get the image and have to convert to some base64 url and need to display in console.. is this possible with this module? or for thii we have any separate module? can you please help me to find ?

**Comment by reviewher** [comment]
@parthivpn we have merged the js-xls library into [js-xlsx](https://github.com/SheetJS/js-xlsx/).  It replicates the API so your existing code should just work.

Since this is related to https://github.com/SheetJS/js-xlsx/issues/137, it's best to close the issue here.
