### ISSUE TITLE
Getting Error :  on "blob.chk(HEADER_SIGNATURE, 'Header Signature: ')"

### ISSUE THREAD

**Issue by parthivpn** [SheetJS/js-xls#91]
While passing or reading xls file , i got following exception 

```
blob.chk(HEADER_SIGNATURE, 'Header Signature: ');
     ^
```

TypeError: blob.chk is not a function
    at check_get_mver (/home/parthiban-zakapps/Proj/test/node_modules/xlsjs/xls.js:1469:7)
    at parse (/home/parthiban-zakapps/Proj/test/node_modules/xlsjs/xls.js:1381:10)

**Comment by reviewher** [comment]
Does this file work with the `xls` binary? To check, from your project directory, run `node_modules/.bin/xls name_of_file` and see if it throws the error.

If you don't see an error, there's an issue with your integration code (possibly passing the wrong type of data).  If you do see an error, there's a bug in the library and we would appreciate it if you could share a file.

On a more general note, we have merged the xls parsing logic into [js-xlsx](https://github.com/SheetJS/js-xlsx/) -- it's a drop-in replacement in browser and in node.  Please upgrade and test against it, if you are seeing problems please raise an issue in the [issue tracker](https://github.com/SheetJS/js-xlsx/issues/)
