### ISSUE TITLE
How to use read from custom column or row?

### ISSUE THREAD

**Issue by alvin992** [SheetJS/js-xls#92]
Hi, I'm Alvin. I'm totaly newbie on using javascript. i followed and read whole issue, but keep failing. until i read ajax.html, and i found the way to import xlsx file. now i need to read 1 data from a cell or any cell in a sheet. May anyone tell me the simple javascript to read custom column or row or cell, from file until read data.

**Comment by reviewher** [comment]
To read a specific cell, suppose that your workbook is the variable `workbook`.  Then, at a high level you have to get the worksheet, then find the cell, then get the values you want.

1) to get the specific worksheet, use with `workbook.Sheets[name_of_worksheet]`.  So if the name is `"Sheet1"` you get the worksheet with

```js
var worksheet = workbook.Sheets["Sheet1"];
``` 

If you want the first worksheet but don't know the name, the workbook object has a `SheetNames` array of sheet names, so you can find the worksheet with:

```js
var first_worksheet = workbook.Sheets[workbook.SheetNames[0]];
```

2) the worksheet is a big object whose keys are cell addresses and whose values are cell objects.  By cell addresses we mean the A1-style address that Excel normally uses.  So to get the cell B2:

```js
var B2 = first_worksheet["B2"];
```

There are utility functions to take numbers and convert them to that string representation.

3) Once you have the cell, the `v` property is the raw value.  If the cell is formatted, the `w` property holds the formatted text. So to get the raw and text values:

```js
var B2_value = B2.v;
var B2_text = B2.w;
```

We have merged js-xls into https://github.com/sheetjs/js-xlsx so please upgrade and report an issue there if you need further assistance
