### ISSUE TITLE
Error in online demo while converting excel data into Json format

### ISSUE THREAD

**Issue by kumarselvarajs** [SheetJS/js-xls#93]
Hi  i have tried converting a excel file into a json format data in the live demo. Share the below screen shot in the console.     Note: My excel has 371 records init, but if try a excel file with 20records its working fine.  
![image](https://cloud.githubusercontent.com/assets/19662514/15667129/d26a0d4c-2714-11e6-98cd-dd895fa49a51.png)

**Comment by iposton** [comment]
I am getting the same error on the demo. Any suggestions?

**Comment by iposton** [comment]
I found this demo that works converting excel to json [http://oss.sheetjs.com/js-xlsx/]( http://oss.sheetjs.com/js-xlsx/) looks exactly like the same ui of the demo found on this repo.

**Comment by reviewher** [comment]
@kumarselvarajs please check against http://oss.sheetjs.com/js-xlsx/ -- we merged all of the XLS handling into the XLSX library
