### ISSUE TITLE
Unable to parse .xlsx file. //11400 Uncaught Error: Unsupported file P

### ISSUE THREAD

**Issue by testcase117** [SheetJS/js-xls#94]
I am trying to create a code from scratch to read the contents of a normal excel file but am unable to even read it. I've used the readme for xlsx.js available for github to guide myself and come up with the following code.

https://github.com/SheetJS/js-xlsx/files/308396/my_code.txt

The error lies in the 46th line as pointed out by the comment in that line, where I've tried to read the excel file as instructed in the readme section.

Following is a quick-link for xlsx.js src. The error comes out from the exception mentioned in the line 11400 of it.

http://oss.sheetjs.com/js-xlsx/xlsx.js

Can somebody please help me with this

**Comment by reviewher** [comment]
This library is for XLS only.  Please raise an issue [there](https://github.com/SheetJS/js-xlsx/issues)
