### ISSUE TITLE
how to create a progress bar into loading handlefile?

### ISSUE THREAD

**Issue by joefreire** [SheetJS/js-xls#95]
i want create a progress bar into loading handlefile, how i can to this?

**Comment by SheetJSDev** [comment]
There are no progress events, so a progress bar would be tricky.  http://oss.sheetjs.com/ shows a simple spin animation while work happens in a web worker.  Basically it uses http://spin.js.org/, creating a spinner before sending work off to the webworker and stopping the spinner at the end.

js-xls has been merged into [js-xlsx](https://github.com/SheetJS/js-xlsx) so please re-raise an issue there.  It is a drop-in replacement, the browser code exposes the XLS variable and the API is exactly the same.
