### ISSUE TITLE
Uncaught Header Signature

### ISSUE THREAD

**Issue by PawanWagh** [SheetJS/js-xls#99]
I am getting this error on my console:
xls.js?_=1468061647592:202 Uncaught Header Signature: Expected d0cf11e0a1b11ae1 saw 504b030414000600

**Comment by msaah85** [comment]
I getting the same error.. any help?

**Comment by reviewher** [comment]
@PawanWagh @msaah85 the signature 504b030414000600 corresponds to one of the newer file formats like xlsx or xlsb.  This project just handles the older XLS formats.  We recommend switching to https://github.com/sheetjs/js-xlsx which combines this support with XLSX and other formats.
